In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("play_tennis.csv")

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df.drop(columns=['day'],inplace=True)

In [36]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [7]:
# Look UP Table
# finds
# P(Yes)
# P(No)

In [10]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [14]:
total = df['play'].value_counts().sum()
Y = df['play'].value_counts().iloc[0]
N = df['play'].value_counts().iloc[1]

In [19]:
PY = Y / total
PN = N / total

In [31]:
# Outlook

Total_NO = pd.crosstab(df['outlook'], df['play']).sum()['No']
Total_Yes = pd.crosstab(df['outlook'], df['play']).sum()['Yes']

Overcast_No = pd.crosstab(df['outlook'], df['play']).loc['Overcast', 'No']

Rain_No = pd.crosstab(df['outlook'], df['play']).loc['Rain', 'No']

Sunny_No = pd.crosstab(df['outlook'], df['play']).loc['Sunny', 'No']

Overcast_Yes = pd.crosstab(df['outlook'], df['play']).loc['Overcast', 'Yes']

Rain_Yes = pd.crosstab(df['outlook'], df['play']).loc['Rain', 'Yes']

Sunny_Yes = pd.crosstab(df['outlook'], df['play']).loc['Sunny', 'Yes']

In [32]:
PON = Overcast_No / Total_NO
PRN = Rain_No / Total_NO
PSN = Sunny_No / Total_NO

POY = Overcast_Yes / Total_Yes
PRY = Rain_Yes / Total_Yes
PSY = Sunny_Yes / Total_Yes

In [34]:
# TEMP

Total_T_NO = pd.crosstab(df['temp'], df['play']).sum()['No']
Total_T_Yes = pd.crosstab(df['temp'], df['play']).sum()['Yes']

Hot_No = pd.crosstab(df['temp'], df['play']).loc['Hot', 'No']

Mild_No = pd.crosstab(df['temp'], df['play']).loc['Mild', 'No']

Cool_No = pd.crosstab(df['temp'], df['play']).loc['Cool', 'No']

Hot_Yes = pd.crosstab(df['temp'], df['play']).loc['Hot', 'Yes']

Mild_Yes = pd.crosstab(df['temp'], df['play']).loc['Mild', 'Yes']

Cool_Yes = pd.crosstab(df['temp'], df['play']).loc['Cool', 'Yes']

In [47]:
PHN = Hot_No / Total_T_NO
PMN = Mild_No / Total_T_NO
PCN = Cool_No / Total_T_NO

PHY = Hot_Yes / Total_T_Yes
PMY = Mild_Yes / Total_T_Yes
PCY = Cool_Yes / Total_T_Yes

In [48]:
# Humidity


Total_H_NO = pd.crosstab(df['humidity'], df['play']).sum()['No']
Total_H_Yes = pd.crosstab(df['humidity'], df['play']).sum()['Yes']

High_No = pd.crosstab(df['humidity'], df['play']).loc['High', 'No']

Normal_No = pd.crosstab(df['humidity'], df['play']).loc['Normal', 'No']



High_Yes = pd.crosstab(df['humidity'], df['play']).loc['High', 'Yes']

Normal_Yes = pd.crosstab(df['humidity'], df['play']).loc['Normal', 'Yes']

In [49]:
PHHN = High_No / Total_H_NO
PNN = Normal_No / Total_H_NO


PHHY = High_Yes / Total_H_Yes
PNY = Normal_Yes / Total_H_Yes

In [50]:
# wind

Total_W_NO = pd.crosstab(df['wind'], df['play']).sum()['No']
Total_W_Yes = pd.crosstab(df['wind'], df['play']).sum()['Yes']

Weak_No = pd.crosstab(df['wind'], df['play']).loc['Weak', 'No']

Strong_No = pd.crosstab(df['wind'], df['play']).loc['Strong', 'No']



Weak_Yes = pd.crosstab(df['wind'], df['play']).loc['Weak', 'Yes']

Strong_Yes = pd.crosstab(df['wind'], df['play']).loc['Strong', 'Yes']

In [54]:
PWN = Weak_No / Total_W_NO
PSN = Strong_No / Total_W_NO

PWY = Weak_Yes / Total_W_Yes
PSY = Strong_Yes / Total_W_Yes

In [55]:
# For OutLook = Sunny, Temp=HOt, Humadity = High , Wind = Weak

PYes = PY * PSY * PHY * PHHY * PWY
PNo = PN * PSN * PHN * PHHN * PWN

In [56]:
PYes

np.float64(0.015873015873015872)

In [46]:
PNo

np.float64(0.02742857142857143)